import type { PlanFile } from "@ukemi/domain";

/**
 * jj's diff-editor protocol, driven non-interactively.
 *
 * jj hands a "diff editor" two directories — `left` (the before tree) and
 * `right` (the after tree, writable) — and waits for the process to exit;
 * whatever `right` then contains becomes the selected content.
 *
 * The draft (§7) worried about fitting that wait into a Tauri window's
 * lifecycle. It does not have to fit: the UI collects the hunk selection
 * *before* jj is invoked, so the "editor" never shows a window. It is a fixed
 * shell script that copies a pre-computed plan over `right` and exits. No IPC,
 * no second window, no lifecycle to reconcile.
 *
 * The plan directory holds:
 *   write/<path>   content to place at <path> in `right`
 *   DELETE         newline-separated paths to remove from `right`
 *   REVERT         newline-separated paths to restore from `left`
 * Anything named in none of them is left as jj staged it. `JJ-INSTRUCTIONS`,
 * which jj also puts in `right`, is untouched — jj removes it itself.
 *
 * REVERT rather than writing the old bytes: it is exact for a binary file, and
 * it is the only way to express "this change deleted the file and I am not
 * taking that deletion", where `right` has no copy to edit.
 */
export const PLAN_TOOL_SCRIPT = `#!/bin/sh
# Generated by Ukemi. Applies a pre-decided hunk selection to jj's \`right\` tree.
# usage: <script> <plandir> <left> <right>
set -eu
PLAN="$1"; LEFT="$2"; RIGHT="$3"
if [ -f "$PLAN/DELETE" ]; then
  while IFS= read -r p; do
    [ -n "$p" ] || continue
    rm -f "$RIGHT/$p"
  done < "$PLAN/DELETE"
fi
if [ -f "$PLAN/REVERT" ]; then
  while IFS= read -r p; do
    [ -n "$p" ] || continue
    if [ -e "$LEFT/$p" ]; then
      mkdir -p "$RIGHT/$(dirname "$p")"
      cp "$LEFT/$p" "$RIGHT/$p"
      # jj hands out \`left\` read-only; the copy must not inherit that.
      chmod u+w "$RIGHT/$p"
    else
      rm -f "$RIGHT/$p"
    fi
  done < "$PLAN/REVERT"
fi
if [ -d "$PLAN/write" ]; then
  ( cd "$PLAN/write" && find . -type f -print ) | sed 's|^\\./||' | while IFS= read -r p; do
    mkdir -p "$RIGHT/$(dirname "$p")"
    cp "$PLAN/write/$p" "$RIGHT/$p"
    chmod u+w "$RIGHT/$p"
  done
fi
exit 0
`;

/** The merge-tool name Ukemi registers for the duration of one command. */
export const PLAN_TOOL_NAME = "ukemi-plan";

/**
 * What a `PlanPreparer` hands back: a materialised plan and how to invoke it.
 *
 * `dispose` removes the temp directory. It is called even when jj fails, so a
 * cancelled split does not leave the user's tree contents in `/tmp`.
 */
export interface PreparedPlan {
  readonly planDir: string;
  readonly scriptPath: string;
  dispose(): Promise<void>;
}

/**
 * Materialises a plan on disk.
 *
 * A seam because the webview cannot write files — the Tauri implementation
 * crosses into Rust, and the Node one is used by tests. Both write the same
 * `PLAN_TOOL_SCRIPT`, so only the plumbing differs; nothing about hunk
 * selection lives on either side of the seam.
 */
export type PlanPreparer = (files: readonly PlanFile[]) => Promise<PreparedPlan>;

/**
 * The `--config` argv that points jj at a prepared plan.
 *
 * Passed per invocation rather than written to the repo's config, so an
 * interrupted split cannot leave a stale `ui.diff-editor` behind that would
 * hijack the user's next `jj split` in a terminal.
 */
export function planToolArgs(plan: PreparedPlan): string[] {
  const args = JSON.stringify([plan.planDir, "$left", "$right"]);
  return [
    "--config",
    `merge-tools.${PLAN_TOOL_NAME}.program=${plan.scriptPath}`,
    "--config",
    `merge-tools.${PLAN_TOOL_NAME}.edit-args=${args}`,
    "--tool",
    PLAN_TOOL_NAME,
  ];
}
